# Провайдер экономики. LuckyEco или Vault.
economy-editor: LuckyEco

# Кастомные теги для /ah search
# Сначала то что в поиске, потом тег на который это заменится
# В примере /ah search test покажет все камни на аукционе.
#
# Чтобы понять какие у предмета теги, пишите /ah admin getTags с правами "liteauction.admin"
custom_tags:
  # пвп предметы
  "взрывная трапка": "item-type:explosive_trap"
  "взрывка": "item-type:explosive_trap"
  "трапка": "item-type:alternative_trap"
  "стан": "item-type:stan"
  "оглушение": "item-type:stan"
  "снежок": "item-type:snowball"
  "ком снега": "item-type:snowball"
  "взрывная штучка": "item-type:explosive_stuff"
  "пузырь опыта": "item-type:bottle"
  "светильник джейка": "item-type:jake"
  "явка": "item-type:jake"

  # динамит
  "ашка": "tnt:a"
  "динамит а": "tnt:a"
  "динамит a": "tnt:a"
  "бешка": "tnt:b"
  "динамит б": "tnt:b"
  "динамит б2": "tnt:b2"
  "динамит b": "tnt:b"
  "динамит b2": "tnt:b2"
  "динамит с4": "tnt:c4"
  "динамит c4": "tnt:c4"
  "с4 взрывчатка": "tnt:c4"
  "c4 взрывчатка": "tnt:c4"
  "сишка": "tnt:c4"
  "волна": "tnt:wave"
  "разрывная волна": "tnt:wave"
  "ледяная волна": "tnt:ice"
  "стиллер": "tnt:stealer"
  "надежный стиллер": "tnt:luck_stealer"
  "взрывчатое вещество": "tnt:explosive"
  "блок пороха": "tnt:explosive"

  # опыт
  "опыт": "experience_bottle"
  "15": "level:15"
  "опыт 15": "level:15"
  "бутылочка с 15 ур опыта": "level:15"
  "бутылочка с 15 лвл": "level:15"
  "30": "level:30"
  "опыт 30": "level:30"
  "бутылочка с 30 ур опыта": "level:30"
  "бутылочка с 30 лвл": "level:30"
  "50": "level:50"
  "опыт 50": "level:50"
  "бутылочка с 50 ур опыта": "level:50"
  "бутылочка с 50 лвл": "level:50"
  "100": "level:100"
  "опыт 100": "level:100"
  "бутылочка с 100 ур опыта": "level:100"
  "бутылочка с 100 лвл": "level:100"

  # сферы и талисманы
  "сфера": "holysfers:1"
  "талисман": "holysfers:1,totem_of_undying"
  "тотем": "totem_of_undying"
  "обычная сфера": "pdc: holysfers:rarity:default"
  "эпическая сфера": "pdc: holysfers:rarity:epic"
  "легендарная сфера": "pdc: holysfers:rarity:legendary"
  "мифическая сфера": "pdc: holysfers:rarity:mythic"
  "сфера на урон": "pdc: holysfers:damage:"
  "сфера на урон 1": "pdc: holysfers:damage:1"
  "сфера на урон 2": "pdc: holysfers:damage:2"
  "сфера на урон 3": "pdc: holysfers:damage:3"
  "сфера на броню": "pdc: holysfers:armor:"
  "сфера на броню 1": "pdc: holysfers:armor:1"
  "сфера на броню 2": "pdc: holysfers:armor:2"
  "сфера на броню 3": "pdc: holysfers:armor:3"
  "сфера на спешку": "pdc: holysfers:haste:"
  "сфера на спешку 1": "pdc: holysfers:haste:1"
  "сфера на спешку 2": "pdc: holysfers:haste:2"
  "сфера на спешку 3": "pdc: holysfers:haste:3"
  "сфера на скорость": "pdc: holysfers:speed:"
  "сфера на скорость 1": "pdc: holysfers:speed:1"
  "сфера на скорость 2": "pdc: holysfers:speed:2"
  "сфера на скорость 3": "pdc: holysfers:speed:3"
  "сфера на скорость атаки": "pdc: holysfers:attack_speed:"
  "сфера на скорость атаки 1": "pdc: holysfers:attack_speed:1"
  "сфера на скорость атаки 2": "pdc: holysfers:attack_speed:2"
  "сфера на скорость атаки 3": "pdc: holysfers:attack_speed:3"
  "сфера на здоровье": "pdc: holysfers:health:"
  "сфера на здоровье 1": "pdc: holysfers:health:1"
  "сфера на здоровье 2": "pdc: holysfers:health:2"
  "сфера на здоровье 3": "pdc: holysfers:health:3"
  "сфера флеша": "holysfers:1,head: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNzc0MDBlYTE5ZGJkODRmNzVjMzlhZDY4MjNhYzRlZjc4NmYzOWY0OGZjNmY4NDYwMjM2NmFjMjliODM3NDIyIn19fQ=="
  "сфера цербера": "holysfers:1,head: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYjA5NWE3ZmQ5MGRhYTFiYmU3MDY5MDg5NzQwZTA1ZDBiZmM2NjI5NmVlM2M0MGVlNzFhNGUwYTY2MTZiMmJiYyJ9fX0="
  "талисман инфинити": "holysfers:1,name: §x§B- §x§BТ§x§B§Fа§x§Cл§x§Dи§x§Dс§x§Eм§x§Eа§x§Fн §x§Fɪ§x§Eɴ§x§Eғ§x§Dɪ§x§Dɴ§x§Cɪ§x§B§Fᴛ§x§Bʏ §x§B-"
  "талисман infinity": "holysfers:1,name: §x§B- §x§BТ§x§B§Fа§x§Cл§x§Dи§x§Dс§x§Eм§x§Eа§x§Fн §x§Fɪ§x§Eɴ§x§Eғ§x§Dɪ§x§Dɴ§x§Cɪ§x§B§Fᴛ§x§Bʏ §x§B-"
  "талисман этернити": "holysfers:1,name: §x§C§A- §x§D§CТ§x§D§Fа§x§D§Eл§x§Eи§x§Eс§x§E§D§Aм§x§F§Dа§x§Fн §x§Fᴇ§x§F§Dᴛ§x§E§D§Aᴇ§x§Eʀ§x§Eɴ§x§D§Eɪ§x§D§Fᴛ§x§D§Cʏ §x§C§A-"
  "талисман eternity": "holysfers:1,name: §x§C§A- §x§D§CТ§x§D§Fа§x§D§Eл§x§Eи§x§Eс§x§E§D§Aм§x§F§Dа§x§Fн §x§Fᴇ§x§F§Dᴛ§x§E§D§Aᴇ§x§Eʀ§x§Eɴ§x§D§Eɪ§x§D§Fᴛ§x§D§Cʏ §x§C§A-"
  "талисман стингер": "holysfers:1,name: §x§F§F- §x§F§FТ§x§F§Fа§x§F§Fл§x§F§Fи§x§F§F§Cс§x§F§F§Fм§x§F§Fа§x§F§Fн §x§F§Fs§x§F§Fᴛ§x§F§F§Eɪ§x§F§F§Aɴ§x§F§Fɢ§x§F§Fᴇ§x§F§Fʀ §x§F§F-"
  "талисман stinger": "holysfers:1,name: §x§F§F- §x§F§FТ§x§F§Fа§x§F§Fл§x§F§Fи§x§F§F§Cс§x§F§F§Fм§x§F§Fа§x§F§Fн §x§F§Fs§x§F§Fᴛ§x§F§F§Eɪ§x§F§F§Aɴ§x§F§Fɢ§x§F§Fᴇ§x§F§Fʀ §x§F§F-"

  # кастом предметы без категории
  "осколочное яйцо": "oskilegg:1"
  "осколочное яйцо энда": "enderegg:1"
  "ножницы садовода": "shears"
  "бессметрия": "bessmertie:1"
  "руна бессметрия": "bessmertie:1"
  "универсальный ключ": "pdc: kotikdang:unick:1"
  "предмет ивента": "head: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOTczNGY3YjQ0OTQ3MmNjMGI0NDRhMTNiYzc2YWY1NDcxMDA4MTEyMDc0NTM3YWJkNTM1ZTc3N2U0ZGRkNWQyOCJ9fX0="
  "ивент поинт": "head: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOTczNGY3YjQ0OTQ3MmNjMGI0NDRhMTNiYzc2YWY1NDcxMDA4MTEyMDc0NTM3YWJkNTM1ZTc3N2U0ZGRkNWQyOCJ9fX0="

  # хранитель опыта
  "охотник": "expkeeper-hunter:1"
  "снеговик": "expkeeper-snowman:1"
  "иллюминатор": "expkeeper-illuminator:1"
  "эндермен": "expkeeper-enderman:1"
  "антифантом": "expkeeper-antifantom:1"
  "телекинез": "expkeeper-telekines:1"
  "гравитация": "expkeeper-gravity:1"
  "вампиризм": "expkeeper-vampire:1"
  "справедливость": "expkeeper-justice:1"
  "артефакт": "expkeeper-artefact:1"

  # донат предметы
  "ботинки инфинити": "name: §x§B- §x§BБ§x§B§Fо§x§Cт§x§A§Dи§x§C§D§Dн§x§E§Eк§x§Fи §x§F§BI§x§Fɴ§x§E§Eғ§x§C§D§Dɪ§x§A§Dɴ§x§Cɪ§x§B§Fᴛ§x§Bʏ §x§B-"
  "ботинки infinity": "name: §x§B- §x§BБ§x§B§Fо§x§Cт§x§A§Dи§x§C§D§Dн§x§E§Eк§x§Fи §x§F§BI§x§Fɴ§x§E§Eғ§x§C§D§Dɪ§x§A§Dɴ§x§Cɪ§x§B§Fᴛ§x§Bʏ §x§B-"
  "поножи инфинити": "name: §x§B- §x§BП§x§Cо§x§C§Bн§x§A§Dо§x§D§Eж§x§F§E§Bи §x§FI§x§Fɴ§x§F§E§Bғ§x§D§Eɪ§x§A§Dɴ§x§C§Bɪ§x§Cᴛ§x§Bʏ §x§B-"
  "поножи infinity": "name: §x§B- §x§BП§x§Cо§x§C§Bн§x§A§Dо§x§D§Eж§x§F§E§Bи §x§FI§x§Fɴ§x§F§E§Bғ§x§D§Eɪ§x§A§Dɴ§x§C§Bɪ§x§Cᴛ§x§Bʏ §x§B-"
  "нагрудник инфинити": "name: §x§B- §x§BН§x§B§Eа§x§Cг§x§C§Fр§x§B§Dу§x§D§Eд§x§F§E§Aн§x§Fи§x§F§Bк §x§FI§x§F§E§Aɴ§x§D§Eғ§x§B§Dɪ§x§C§Fɴ§x§Cɪ§x§B§Eᴛ§x§Bʏ §x§B-"
  "нагрудник infinity": "name: §x§B- §x§BН§x§B§Eа§x§Cг§x§C§Fр§x§B§Dу§x§D§Eд§x§F§E§Aн§x§Fи§x§F§Bк §x§FI§x§F§E§Aɴ§x§D§Eғ§x§B§Dɪ§x§C§Fɴ§x§Cɪ§x§B§Eᴛ§x§Bʏ §x§B-"
  "шлем инфинити": "name: §x§B- §x§BШ§x§Cл§x§C§Eе§x§C§D§Bм §x§E§EI§x§Fɴ§x§Fғ§x§E§Eɪ§x§C§D§Bɴ§x§C§Eɪ§x§Cᴛ§x§Bʏ §x§B-"
  "шлем infinity": "name: §x§B- §x§BШ§x§Cл§x§C§Eе§x§C§D§Bм §x§E§EI§x§Fɴ§x§Fғ§x§E§Eɪ§x§C§D§Bɴ§x§C§Eɪ§x§Cᴛ§x§Bʏ §x§B-"
  "шлем солнца": "name: §x§F§F§C• Шлем солнца •"
  "меч этернити": "name: §x§C§A- §x§D§BМ§x§D§Cе§x§Eч §x§E§D§Bᴇ§x§Fᴛ§x§F§Fᴇ§x§Fʀ§x§E§D§Bɴ§x§Eɪ§x§D§Cᴛ§x§D§Bʏ §x§C§A-"
  "меч eternity": "name: §x§C§A- §x§D§BМ§x§D§Cе§x§Eч §x§E§D§Bᴇ§x§Fᴛ§x§F§Fᴇ§x§Fʀ§x§E§D§Bɴ§x§Eɪ§x§D§Cᴛ§x§D§Bʏ §x§C§A-"
  "кирка этернити": "name: §x§C§A- §x§D§DК§x§D§Cи§x§Eр§x§Eк§x§E§D§Bа §x§Fᴇ§x§F§Fᴛ§x§Fᴇ§x§F§Dʀ§x§E§Bɴ§x§Eɪ§x§D§Eᴛ§x§D§Eʏ §x§C§A-"
  "кирка eternity": "name: §x§C§A- §x§D§DК§x§D§Cи§x§Eр§x§Eк§x§E§D§Bа §x§Fᴇ§x§F§Fᴛ§x§Fᴇ§x§F§Dʀ§x§E§Bɴ§x§Eɪ§x§D§Eᴛ§x§D§Eʏ §x§C§A-"

  # рюкзаки
  "рюкзак": "pdc: holybackpack:backpack-level:"
  "рюкзак 1 уровень": "name: §x§D§A§BР§x§E§Cю§x§E§D§Cк§x§F§C§Dз§x§E§Cа§x§D§A§Bк (I уровень)"
  "рюкзак мини": "name: §x§D§A§BР§x§E§Cю§x§E§D§Cк§x§F§C§Dз§x§E§Cа§x§D§A§Bк (I уровень)"
  "рюкзак 2 уровень": "name: §x§B§C§BР§x§B§C§Dю§x§C§C§Eк§x§D§Fз§x§B§C§Eа§x§B§C§Bк (II уровень)"
  "рюкзак нормальный": "name: §x§B§C§BР§x§B§C§Dю§x§C§C§Eк§x§D§Fз§x§B§C§Eа§x§B§C§Bк (II уровень)"
  "рюкзак 3 уровень": "name: §x§DР§x§D§Fю§x§E§Aк§x§F§D§Dз§x§Eа§x§Dк (III уровень)"
  "рюкзак большой": "name: §x§DР§x§D§Fю§x§E§Aк§x§F§D§Dз§x§Eа§x§Dк (III уровень)"
  "рюкзак 4 уровень": "name: §x§C§B§AР§x§D§C§Bю§x§E§C§Cк§x§F§D§C§Eз§x§D§B§C§B§Aа§x§C§B§Aк (IV уровень)"
  "рюкзак огромный": "name: §x§C§B§AР§x§D§C§Bю§x§E§C§Cк§x§F§D§C§Eз§x§D§B§C§B§Aа§x§C§B§Aк (IV уровень)"

  # кастомные зачарования
  "фильтр": "pdc: holyenchantments:holyenchantments-filter:"
  "книга фильтр": "pdc: holyenchantments:holyenchantments-filter:,enchanted_book"
  "зачарование фильтр": "pdc: holyenchantments:holyenchantments-filter:"
  "посев": "pdc: holyenchantments:holyenchantments-sowing:"
  "книга посев": "pdc: holyenchantments:holyenchantments-sowing:,enchanted_book"
  "зачарование посев": "pdc: holyenchantments:holyenchantments-sowing:"
  "деликатный": "pdc: holyenchantments:holyenchantments-delicious:"
  "книга деликатный": "pdc: holyenchantments:holyenchantments-delicious:,enchanted_book"
  "зачарование деликатный": "pdc: holyenchantments:holyenchantments-delicious:"
  "непробиваемый": "pdc: holyenchantments:holyenchantments-impenetrable:"
  "книга непробиваемый": "pdc: holyenchantments:holyenchantments-impenetrable:,enchanted_book"
  "зачарование непробиваемый": "pdc: holyenchantments:holyenchantments-impenetrable:"
  "неразрушимость": "pdc: holyenchantments:holyenchantments-breakless:"
  "книга неразрушимость": "pdc: holyenchantments:holyenchantments-breakless:,enchanted_book"
  "зачарование неразрушимость": "pdc: holyenchantments:holyenchantments-breakless:"
  "опытный": "pdc: holyenchantments:holyenchantments-expboost:"
  "книга опытный": "pdc: holyenchantments:holyenchantments-expboost:,enchanted_book"
  "зачарование опытный": "pdc: holyenchantments:holyenchantments-expboost:"
  "критический": "pdc: holyenchantments:holyenchantments-critical:"
  "книга критический": "pdc: holyenchantments:holyenchantments-critical:,enchanted_book"
  "зачарование критический": "pdc: holyenchantments:holyenchantments-critical:"
  "бур": "pdc: holyenchantments:holyenchantments-boor:"
  "книга бур": "pdc: holyenchantments:holyenchantments-boor:,enchanted_book"
  "зачарование бур": "pdc: holyenchantments:holyenchantments-boor:"
  "автоплавка": "pdc: holyenchantments:holyenchantments-melting:"
  "книга автоплавка": "pdc: holyenchantments:holyenchantments-melting:,enchanted_book"
  "зачарование автоплавка": "pdc: holyenchantments:holyenchantments-melting:"
  "лаваход": "pdc: holyenchantments:holyenchantments-lava-move:"
  "книга лаваход": "pdc: holyenchantments:holyenchantments-lava-move:,enchanted_book"
  "зачарование лаваход": "pdc: holyenchantments:holyenchantments-lava-move:"
  "разрушитель": "pdc: holyenchantments:holyenchantments-destroyer:"
  "книга разрушитель": "pdc: holyenchantments:holyenchantments-destroyer:,enchanted_book"
  "зачарование разрушитель": "pdc: holyenchantments:holyenchantments-destroyer:"
  "магнетизм": "pdc: holyenchantments:holyenchantments-magnet:"
  "книга магнетизм": "pdc: holyenchantments:holyenchantments-magnet:,enchanted_book"
  "зачарование магнетизм": "pdc: holyenchantments:holyenchantments-magnet:"
  "фермер": "pdc: holyenchantments:holyenchantments-fermer:"
  "книга фермер": "pdc: holyenchantments:holyenchantments-fermer:,enchanted_book"
  "зачарование фермер": "pdc: holyenchantments:holyenchantments-fermer:"
  "фармер": "pdc: holyenchantments:holyenchantments-farmer:"
  "книга фармер": "pdc: holyenchantments:holyenchantments-farmer:,enchanted_book"
  "зачарование фармер": "pdc: holyenchantments:holyenchantments-farmer:"
  "самонаводка": "pdc: holyenchantments:holyenchantments-aim:"
  "книга самонаводка": "pdc: holyenchantments:holyenchantments-aim:,enchanted_book"
  "зачарование самонаводка": "pdc: holyenchantments:holyenchantments-aim:"

  # ванильные зачарования
  "защита": "enchantment: protection:"
  "книга защита": "enchantment: protection:,enchanted_book"
  "зачарование защита": "enchantment: protection:"
  "огнеупорность": "enchantment: fire_protection:"
  "книга огнеупорность": "enchantment: fire_protection:,enchanted_book"
  "зачарование огнеупорность": "enchantment: fire_protection:"
  "невесомость": "enchantment: feather_falling:"
  "книга невесомость": "enchantment: feather_falling:,enchanted_book"
  "зачарование невесомость": "enchantment: feather_falling:"
  "взрывоустойчивость": "enchantment: blast_protection:"
  "книга взрывоустойчивость": "enchantment: blast_protection:,enchanted_book"
  "зачарование взрывоустойчивость": "enchantment: blast_protection:"
  "защита от снарядов": "enchantment: projectile_protection:"
  "книга защита от снарядов": "enchantment: projectile_protection:,enchanted_book"
  "зачарование защита от снарядов": "enchantment: projectile_protection:"
  "подводное дыхание": "enchantment: respiration:"
  "книга подводное дыхание": "enchantment: respiration:,enchanted_book"
  "зачарование подводное дыхание": "enchantment: respiration:"
  "подводник": "enchantment: aqua_affinity:"
  "книга подводник": "enchantment: aqua_affinity:,enchanted_book"
  "зачарование подводник": "enchantment: aqua_affinity:"
  "шипы": "enchantment: thorns:"
  "книга шипы": "enchantment: thorns:,enchanted_book"
  "зачарование шипы": "enchantment: thorns:"
  "подводная хотьба": "enchantment: depth_strider:"
  "книга подводная хотьба": "enchantment: depth_strider:,enchanted_book"
  "зачарование подводная хотьба": "enchantment: depth_strider:"
  "ледоход": "enchantment: frost_walker:"
  "книга ледоход": "enchantment: frost_walker:,enchanted_book"
  "зачарование ледоход": "enchantment: frost_walker:"
  "проклятие несъемности": "enchantment: binding_curse:"
  "книга проклятие несъемности": "enchantment: binding_curse:,enchanted_book"
  "зачарование проклятие несъемности": "enchantment: binding_curse:"
  "острота": "enchantment: sharpness:"
  "книга острота": "enchantment: sharpness:,enchanted_book"
  "зачарование острота": "enchantment: sharpness:"
  "небесная кара": "enchantment: smite:"
  "книга небесная кара": "enchantment: smite:,enchanted_book"
  "зачарование небесная кара": "enchantment: smite:"
  "бич членистоногих": "enchantment: bane_of_arthropods:"
  "книга бич членистоногих": "enchantment: bane_of_arthropods:,enchanted_book"
  "зачарование бич членистоногих": "enchantment: bane_of_arthropods:"
  "отдача": "enchantment: knockback:"
  "книга отдача": "enchantment: knockback:,enchanted_book"
  "зачарование отдача": "enchantment: knockback:"
  "заговор огня": "enchantment: fire_aspect:"
  "книга заговор огня": "enchantment: fire_aspect:,enchanted_book"
  "зачарование заговор огня": "enchantment: fire_aspect:"
  "добыча": "enchantment: looting:"
  "книга добыча": "enchantment: looting:,enchanted_book"
  "зачарование добыча": "enchantment: looting:"
  "разящий клинок": "enchantment: sweeping:"
  "книга разящий клинок": "enchantment: sweeping:,enchanted_book"
  "зачарование разящий клинок": "enchantment: sweeping:"
  "эффективность": "enchantment: efficiency:"
  "книга эффективность": "enchantment: efficiency:,enchanted_book"
  "зачарование эффективность": "enchantment: efficiency:"
  "шелковое касание": "enchantment: silk_touch:"
  "книга шелковое касание": "enchantment: silk_touch:,enchanted_book"
  "зачарование шелковое касание": "enchantment: silk_touch:"
  "прочность": "enchantment: unbreaking:"
  "книга прочность": "enchantment: unbreaking:,enchanted_book"
  "зачарование прочность": "enchantment: unbreaking:"
  "удача": "enchantment: fortune:"
  "книга удача": "enchantment: fortune:,enchanted_book"
  "зачарование удача": "enchantment: fortune:"
  "сила": "enchantment: power:"
  "книга сила": "enchantment: power:,enchanted_book"
  "зачарование сила": "enchantment: power:"
  "откидывание": "enchantment: punch:"
  "книга откидывание": "enchantment: punch:,enchanted_book"
  "зачарование откидывание": "enchantment: punch:"
  "воспланемение": "enchantment: flame:"
  "книга воспланемение": "enchantment: flame:,enchanted_book"
  "зачарование воспланемение": "enchantment: flame:"
  "бесконечность": "enchantment: infinity:"
  "книга бесконечность": "enchantment: infinity:,enchanted_book"
  "зачарование бесконечность": "enchantment: infinity:"
  "везучий рыбак": "enchantment: luck_of_the_sea:"
  "книга везучий рыбак": "enchantment: luck_of_the_sea:,enchanted_book"
  "зачарование везучий рыбак": "enchantment: luck_of_the_sea:"
  "приманка": "enchantment: lure:"
  "книга приманка": "enchantment: lure:,enchanted_book"
  "зачарование приманка": "enchantment: lure:"
  "верность": "enchantment: loyalty:"
  "книга верность": "enchantment: loyalty:,enchanted_book"
  "зачарование верность": "enchantment: loyalty:"
  "пронзание": "enchantment: impaling:"
  "книга пронзание": "enchantment: impaling:,enchanted_book"
  "зачарование пронзание": "enchantment: impaling:"
  "тягун": "enchantment: riptide:"
  "книга тягун": "enchantment: riptide:,enchanted_book"
  "зачарование тягун": "enchantment: riptide:"
  "громовержец": "enchantment: channeling:"
  "книга громовержец": "enchantment: channeling:,enchanted_book"
  "зачарование громовержец": "enchantment: channeling:"
  "починка": "enchantment: mending:"
  "книга починка": "enchantment: mending:,enchanted_book"
  "зачарование починка": "enchantment: mending:"
  "проклятие утраты": "enchantment: vanishing_curse:"
  "книга проклятие утраты": "enchantment: vanishing_curse:,enchanted_book"
  "зачарование проклятие утраты": "enchantment: vanishing_curse:"
  "тройной выстрел": "enchantment: multishot:"
  "книга тройной выстрел": "enchantment: multishot:,enchanted_book"
  "зачарование тройной выстрел": "enchantment: multishot:"
  "быстрая перезарядка": "enchantment: quick_charge:"
  "книга быстрая перезарядка": "enchantment: quick_charge:,enchanted_book"
  "зачарование быстрая перезарядка": "enchantment: quick_charge:"
  "пронзающая стрела": "enchantment: piercing:"
  "книга пронзающая стрела": "enchantment: piercing:,enchanted_book"
  "зачарование пронзающая стрела": "enchantment: piercing:"
  "скорость души": "enchantment: soul_speed:"
  "книга скорость души": "enchantment: soul_speed:,enchanted_book"
  "зачарование скорость души": "enchantment: soul_speed:"

  # зелья
  "скорость": "potion: speed"
  "зелье скорости": "potion: speed"
  "замедление": "potion: slow"
  "зелье замедления": "potion: slow"
  "прыгучесть": "potion: jump_boost"
  "зелье прыгучести": "potion: jump_boost"
  "сила": "potion: strength"
  "зелье силы": "potion: strength"
  "исцеление": "potion: instant_health"
  "зелье исцеления": "potion: instant_health"
  "моментальный урон": "potion: instant_damage"
  "зелье моментального урона": "potion: instant_damage"
  "регенерация": "potion: regeneration"
  "зелье регенерации": "potion: regeneration"
  "огнестойкость": "potion: fire_resistance"
  "зелье огнестойкости": "potion: fire_resistance"
  "подводное дыхание": "potion: water_breathing"
  "зелье подводного дыхания": "potion: water_breathing"
  "невидимость": "potion: invisibility"
  "зелье невидимости": "potion: invisibility"
  "сопротивление": "potion: resistance"
  "зелье сопротивления": "potion: resistance"
  "отравлене": "potion: poison"
  "зелье отравления": "potion: poison"
  "слабость": "potion: weakness"
  "зелье слабости": "potion: weakness"
  "везение": "potion: luck"
  "зелье везения": "potion: luck"
  "плавное падение": "potion: slow_falling"
  "зелье плавного падения": "potion: slow_falling"
  "зелье победителя": "name: §x§BЗ§x§A§Cе§x§C§Aл§x§Dь§x§A§D§Fе §x§A§E§Aп§x§A§F§Fо§x§B§F§Fб§x§A§F§Fе§x§A§E§Aд§x§A§D§Fи§x§Dт§x§C§Aе§x§A§Cл§x§Bя"

# ВАЖНО:
# Файл assets.json НЕ РЕДАКТИРУЙТЕ, так как это может сломать плагин!
# Если вы все-таки хотите поменять название, то меняйте только русский перевод,
# но на ваш страх и риск.